language: go
go: 1.4
env:
  global:
    - PATH=$HOME/gopath/bin:$PATH
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gifsicle libmagic-dev
  - go get github.com/tools/godep
  - godep restore
script:
  - make test
